### ISSUE TITLE
Ability to retrieve name of interface instead of class

### ISSUE THREAD

**Issue by brandongregoryscott** [IRCraziestTaxi/ts-simple-nameof#24]
It would be nice to be able to retrieve the name of a given interface, instead of only concrete classes or property selectors of an interface/class.

For example:
```typescript
interface User {
    firstName: string;
    lastName: string;
}

const interfaceName = nameof<User>();
```

I haven't looked at the code yet, but I'm not sure if that would force an API change with the current `nameof<TClass>(TClass)` signature. Based on the related package [ts-nameof](https://github.com/dsherret/ts-nameof), I would imagine it's possible.

**Comment by IRCraziestTaxi** [comment]
Hey @brandongregoryscott,

Thanks for using the lib!

The problem here is that `ts-nameof` does compile-time transforms while `ts-simple-nameof` provides a runtime method.

Given that `ts-simple-nameof` works at runtime, it is impossible to rely on type arguments or interfaces as they are purely typescript concepts and do not exist in compiled javascript. I did create this library to be a (as the name implies) very simple to use method for getting the names of properties and later classes as well, but unfortunately it is only as simple as it is because it is a runtime method.

`ts-nameof` appears to be very robust, so if you want features such as the one described by this issue, I would suggest going through the setup process it describes for your stack. It appears to have a comprehensive set of readme instructions for whatever your setup is.

**Comment by brandongregoryscott** [comment]
Ah, bummer! Makes sense, though. Thanks for the explanation. We would've used `ts-nameof`, but we ran into issues trying to get it integrated with our project while leveraging `create-react-app`. For now, we're still loving the benefit of type-safe string representations of fields, functions and classes.

Cheers 👍
