### ISSUE TITLE
Support anonymous functions with ES5 

### ISSUE THREAD

**Issue by MarkVink** [IRCraziestTaxi/ts-simple-nameof#37]
Our company has a shared library with style components to make sure different products have the same look. I'm experiencing an issue with the following piece of code when the project is compiled for ES5. When Es6 is used, it works fine.

```
public ngOnChanges(changes: SimpleChanges): void {
    if (changes[nameof(() => this.min)]) {
        this.minDateTime = this.toStartOf(this.min);
    }
}
```

The underlying issue is that the regex used in the ES5 prop selector in this library does not support the use of anonymous functions. In Javascript, the input for the nameof-function is `function(){return t.min}`. However, the regex expects the format  `function (x) { return x.prop; }`.

My suggestion would be to make the argument optional by changing the regex to `/function\s*\([\w+]?\)\s*\{[\r\n\s]*return\s+\w+\.((\w+\.)*(\w+))/i`

**Comment by michieldondorp** [comment]
@IRCraziestTaxi @Beej126 could either one of you comment on this improvement? We would love to see this minor fix.

**Comment by Beej126** [comment]
@michieldondorp - this is not on my radar anymore... wound up going with an alternative lib: [ts-nameof.macro](https://www.npmjs.com/package/ts-nameof.macro)... see if it does the trick for you

**Comment by IRCraziestTaxi** [comment]
Sorry I am just now getting around to commenting on this; haven't paid attention to my personal or open source projects in quite a while.

I am going to go ahead and close this. I honestly don't see much use for it. The premise of the `nameof` function is to take a type argument and use an appropriate lambda (i.e. `nameof<ClassX>(x => x.prop)`) to extract the property name. So instead of `nameof(() => this.min)` you could just use `nameof<ClassName>(c => c.min)`.
